In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

data = []

for page in range(1, 51):

    if page == 1:
        url = "https://books.toscrape.com/"
    else:
        url = f"https://books.toscrape.com/catalogue/page-{page}.html"

    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    for book in books:
        title = book.find("h3").find("a")["title"]
        price = book.find("p", class_="price_color").text
        rating = book.find("p", class_="star-rating")["class"][1]

        data.append({
            "Title": title,
            "Price": price,
            "Rating": rating
        })

print("Total records:", len(data))

Total records: 1000

In [4]:
df=pd.DataFrame(data)
df

                                                 Title    Price Rating
0                                 A Light in the Attic  Â£51.77  Three
1                                   Tipping the Velvet  Â£53.74    One
2                                           Soumission  Â£50.10    One
3                                        Sharp Objects  Â£47.82   Four
4                Sapiens: A Brief History of Humankind  Â£54.23   Five
..                                                 ...      ...    ...
995  Alice in Wonderland (Alice's Adventures in Won...  Â£55.53    One
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)  Â£57.06   Four
997  A Spy's Devotion (The Regency Spies of London #1)  Â£16.97   Five
998                1st to Die (Women's Murder Club #1)  Â£53.98    One
999                 1,000 Places to See Before You Die  Â£26.08   Five

[1000 rows x 3 columns]

In [8]:
df["Price"]=df["Price"].str.replace("Â£"," ")
df["Price"]

0       51.77
1       53.74
2       50.10
3       47.82
4       54.23
        ...
995     55.53
996     57.06
997     16.97
998     53.98
999     26.08
Name: Price, Length: 1000, dtype: object

In [9]:
df

                                                 Title   Price Rating
0                                 A Light in the Attic   51.77  Three
1                                   Tipping the Velvet   53.74    One
2                                           Soumission   50.10    One
3                                        Sharp Objects   47.82   Four
4                Sapiens: A Brief History of Humankind   54.23   Five
..                                                 ...     ...    ...
995  Alice in Wonderland (Alice's Adventures in Won...   55.53    One
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)   57.06   Four
997  A Spy's Devotion (The Regency Spies of London #1)   16.97   Five
998                1st to Die (Women's Murder Club #1)   53.98    One
999                 1,000 Places to See Before You Die   26.08   Five

[1000 rows x 3 columns]

In [13]:
Rating_map={
    "One":1,
    "Two":2,
    "Three":3,
    "Four":4,
    "Five":5
}
df["Rating"]=df["Rating"].map(Rating_map)

In [14]:
df

                                                 Title   Price  Rating
0                                 A Light in the Attic   51.77       3
1                                   Tipping the Velvet   53.74       1
2                                           Soumission   50.10       1
3                                        Sharp Objects   47.82       4
4                Sapiens: A Brief History of Humankind   54.23       5
..                                                 ...     ...     ...
995  Alice in Wonderland (Alice's Adventures in Won...   55.53       1
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)   57.06       4
997  A Spy's Devotion (The Regency Spies of London #1)   16.97       5
998                1st to Die (Women's Murder Club #1)   53.98       1
999                 1,000 Places to See Before You Die   26.08       5

[1000 rows x 3 columns]

In [15]:
df.isnull().sum()

Title     0
Price     0
Rating    0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.to_csv("book_set.csv",index=False)